# Generated by Django 3.2.8 on 2025-01-05 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商家公告',
                'verbose_name_plural': '商家公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期')),
                ('opening_time', models.TimeField(verbose_name='开始营业时间')),
                ('closing_time', models.TimeField(verbose_name='结束营业时间')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否休息')),
            ],
            options={
                'verbose_name': '营业时间',
                'verbose_name_plural': '营业时间',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商家名称')),
                ('description', models.TextField(blank=True, verbose_name='商家描述')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('logo', models.ImageField(blank=True, upload_to='merchant/logos/', verbose_name='商家logo')),
                ('business_license', models.ImageField(upload_to='merchant/licenses/', verbose_name='营业执照')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商家信息',
                'verbose_name_plural': '商家信息',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('promotion_type', models.CharField(choices=[('discount', '折扣'), ('reduction', '满减'), ('gift', '赠品')], default='discount', max_length=20, verbose_name='活动类型')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='折扣值')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低消费金额')),
                ('reduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='优惠金额')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优惠活动',
                'verbose_name_plural': '优惠活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant')),
            ],
        ),
    ]
